### ISSUE TITLE
NPE on opening virtual objectr

### ISSUE THREAD

**Issue by dudarkoas** [dbickley/OpenEditors#32]
I got virtual objects, which doesn't exists on hard drive. When i'm opening them i get NPE

> !MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".
> !STACK 0
> java.lang.NullPointerException
> at org.eclipse.core.runtime.Path.<init>(Path.java:231)
> at org.eclipse.core.runtime.Path.<init>(Path.java:189)
> at com.deepnoodle.openeditors.ui.EditorViewLabelProvider$EditorStyledLabelProvider.lambda$0(EditorViewLabelProvider.java:170)
> at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
> at com.deepnoodle.openeditors.ui.EditorViewLabelProvider$EditorStyledLabelProvider.updateLabels(EditorViewLabelProvider.java:169)
> at com.deepnoodle.openeditors.ui.EditorViewLabelProvider.updateLabels(EditorViewLabelProvider.java:56)
> at com.deepnoodle.openeditors.ui.EditorTableView.setInput(EditorTableView.java:88)
> at com.deepnoodle.openeditors.ui.EditorPresenter.refresh(EditorPresenter.java:167)
> at com.deepnoodle.openeditors.ui.EditorPresenter.partBroughtToTop(EditorPresenter.java:133)

**Comment by achimmihca** [comment]
Unfortunate error.
Anyhow, I am not working in an Eclipse environment anymore and won't be able to fix this.
Please feel free to fork the repo and add a null-check where necessary. You can find some development guide in README.md

I will happily accept pull requests.

**Comment by achimmihca** [comment]
I added a null check in version 1.0.0.
Please, close this issue if you find that the problem is solved.
